dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

# <https://docs.travis-ci.com/user/languages/python/>
# > If you need to install Python packages, do it via pip and not apt.
before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd test/ &&  pytest --cov pipdate

after_success:
  - bash <(curl -s https://codecov.io/bash)
