version: 2

jobs:

  build:
    working_directory: ~/pipdate
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip pandoc
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .
      # lint
      - run: pylint pipdate/ test/*.py setup.py
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov pipdate
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
